# Generated by Django 4.2.19 on 2025-11-13 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESAMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('admission_year', models.IntegerField()),
                ('graduation_year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('mpesa_number', models.CharField(max_length=15)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('membership_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
